[project]
name = "fairmss"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "inequalipy>=1.0.5",
    "matplotlib>=3.10.7",
    "networkx>=3.6",
    "numpy>=2.3.5",
    "scipy>=1.16.3",
    "seaborn>=0.13.2",
]
